project:
  type: website

website:
  title: "LF10a"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: aa.qmd
        text: aaa
      - href: bb.qmd
        text: bbb

format:
  revealjs:
    include-after-body: libs/backlink.html
    css: libs/styles.css
    logo: libs/_Images/logo-AFBB.svg

publish:
  gh-pages: true
