project:
  type: website

website:
  title: "LF8"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: 01_Willkommen_Struktur.qmd
        text: 01 Willkommen zu LF8 - Themen und Zeitplan
      - href: 02_Algorithmen.qmd
        text: 02 Algorithmen

format:
  revealjs:
    include-after-body: libs/backlink.html
    css: libs/styles.css
    logo: libs/_Images/logo-AFBB.svg

publish:
  gh-pages: true
